-- Keymaps are automatically loaded on the VeryLazy event
-- Default keymaps that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/keymaps.lua
-- Add any additional keymaps here

-- local opts = { silent = true, noremap = true }

-- Reset format keybind
-- vim.keymap.del({ "n", "v" }, "<leader>cf")

-- -- Reset line diagnostic
-- vim.keymap.del("n", "<leader>e", opts)
-- vim.keymap.del("n", "<leader>E")
--
-- -- Reset quit keybind
-- vim.keymap.del("n", "<leader>qq")
--
-- -- Reset terminal
-- vim.keymap.del("n", "<leader>fT")
-- vim.keymap.del("n", "<leader>ft")
-- vim.keymap.del("n", "<c-/>")
-- vim.keymap.del("n", "<c-_>")
--
-- -- Reset tabs
-- vim.keymap.del("n", "<leader><tab>l")
-- vim.keymap.del("n", "<leader><tab>o")
-- vim.keymap.del("n", "<leader><tab>f")
-- vim.keymap.del("n", "<leader><tab>[")
-- vim.keymap.del("n", "<leader><tab>]")
-- vim.keymap.del("n", "<leader><tab>d")
-- vim.keymap.del("n", "<leader><tab><tab>")
--
-- -- Reset changelog
-- vim.keymap.del("n", "<leader>L")
--
-- -- Reset session keybinds
-- vim.keymap.del("n", "<leader>qd", opts)
-- vim.keymap.del("n", "<leader>ql")
-- vim.keymap.del("n", "<leader>qs")
-- vim.keymap.del("n", "<leader>qS")
